### ISSUE TITLE
hxd，能不能搞个抢讲座脚本

### ISSUE THREAD

**Issue by dmliu1028** [ZiyuZ/SEU_Lecture_Monitor#1]

**Comment by ZiyuZ** [comment]
感觉不太合适, 不会提供抢课功能.
其实也就开学几个月抢讲座的人多, 到了年底有的讲座人数都不满, 也不需要抢.

**Comment by ZiyuZ** [comment]
新增了一个定时检查的功能, 用电脑的时候一直挂着就行, 如果检查到有可用的讲座会自动打开浏览器. 手动登录预约基本上也够用了.
